### PR TITLE
Workaround for GHC 9.6.1-alpha3

### LINKED ISSUE #102: Not building with GHC 9.6.1-alpha3
It seems that ad-4.6.3 on hackage and current HEAD (b69fc5659fe886cad9ee10cc42f4472b36595e8c) both fails to compile with GHC 9.6.1-alpha3 (9.6.0.20230210):

```
src/Numeric/AD/Internal/On.hs:40:10: error: [GHC-39999]
    • Could not deduce ‘Num (Scalar (Scalar t))’
        arising from the superclasses of an instance declaration
      from the context: (Mode t, Mode (Scalar t))
        bound by the instance declaration
        at src/Numeric/AD/Internal/On.hs:40:10-49
      Possible fix:
        If the constraint looks soluble from a superclass of the instance context,
        read 'Undecidable instances and loopy superclasses' in the user manual
    • In the instance declaration for ‘Mode (On t)’
   |
40 | instance (Mode t, Mode (Scalar t)) => Mode (On t) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by konn**
It seems GHC 9.6.1-alpha3 becomed more strict on undecidable superclass context.
Paterson-smallness condition seems preventing infer `Num (Scalar (Scalar t))` from `Mode (Scalar t)`.
As [suggested in GHC User's Guide](https://downloads.haskell.org/ghc/9.6.1-alpha3/docs/users_guide/exts/instances.html#undecidable-instances-and-loopy-superclasses), this PR resolves this issue just by adding the seemingly derivable (but deliberately uninferred) `Num (Scalar (Scalar t))` constraint to the superclass constraints.

This fixes #102.

### CODE REVIEW

**Review by RyanGlScott — APPROVED** [review]
Thanks!
